# Generated by Django 5.1.7 on 2025-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='metadata_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
